### ISSUE TITLE
gof error - can't open tmp file - gVim, Win10

### ISSUE THREAD

**Issue by AssailantLF** [justinmk/vim-gtfo#34]
Whenever I attempt to use the gof command, Windows Explorer opens to *C:\*, and goF opens to *My Documents*. Both give the same error in Vim:

    Error detected while processing function gtfo#open#file:
    line   20:
    E484: Can't open file C:\Users\Austin\AppData\Local\Temp\VIo10CC.tmp

I'm running a regular install of Vim for Windows, with vim-plug. I tried disabling all other plugins, settings, and running with *Administrator Privileges*. The docs say that being unable to open a temp file in Windows is probably due to *"wrong escaping of special characters for cmd.exe"*, or maybe it has something to do with Windows 10?

**Comment by justinmk** [comment]
`C:\Users\Austin\AppData\Local\Temp\VIo10CC.tmp` does not look like wrong escaping to me :) 

What is the output of: 

    :set shellslash?

Note that Vim is notorious on Windows for having temp-file breakage like this, and it's why gtfo.vim does backflips to avoid `system()` on Windows (it uses `:!` instead). The reason this is happening for you, though, is that `executable('cygpath')` returns non-zero so gtfo.vim thinks it is running inside cygwin. I guess maybe I should re-think that condition, but can you say why `cygpath` is in your path if your not running in cygwin? Is that intentional, and for what reason?

**Comment by AssailantLF** [comment]
`noshellslash`

And after some experimenting, I figured out why the cygpath is being set. When you install Git-for-Windows, you have 3 choices with regards to the PATH:

![options](https://i.imgur.com/OOwlzXp.png)

If you choose the third, a bash.exe gets added to the PATH, and that causes the problem. If I install with a different option, it works correctly.

**Comment by AssailantLF** [comment]
So have you figured a work around for this, or maybe a vimrc snippet to fix it on my end? Currently, I've just reinstalled Git without Unix tools in my path, which is more of a work around than a real fix.

I don't really rely on unix tools, but it's slightly more convenient to always use `ls`, `rm`, `mv`, etc. instead of the Windows equivalents.

**Comment by AssailantLF** [comment]
Oh, so I noticed that I completely misunderstood or misread what you said originally about `executable('cygpath')`. But the issue is basically the same. If Git for Windows installs cygpath to your PATH, this happens.

So now that I'm not being dumb, I added a condition to `open.vim` on line 105 to check if "Git" is in cygpath's path, so now it's

    if executable('cygpath') && (stridx(exepath('cygpath'), 'Git') == -1)

and it seems to have fixed the problem! Feel free to add it in as an update or whatever if you want.
